import './globals.scss'
import { Nunito } from 'next/font/google'

const nunitoFont = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'DevChallenge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={nunitoFont.className}>{children}</body>
    </html>
  )
}
